// Auto-generated from the BNF scanner universe — full S&P MidCap 400 +
// SmallCap 600 constituents. Edit this file to grow/shrink the universe,
// then redeploy the edge function. Kept as .ts (not .json) because
// Supabase's Deno runtime doesn't support JSON-import attributes yet.

export interface UniverseEntry {
  ticker: string;
  sector: string;
  sectorEtf: string;
}

export const UNIVERSE: UniverseEntry[] = [
  { ticker: 'AA', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'AAL', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AAMI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'AAON', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AAP', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'AAT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'ABCB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ABG', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'ABM', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ABR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ACA', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ACAD', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ACHC', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ACI', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'ACIW', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ACLS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ACM', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ACMR', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ACT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ADAM', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'ADC', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'ADEA', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ADMA', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ADNT', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'ADT', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'ADUS', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AEIS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'AEO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'AESI', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'AFG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'AGCO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AGO', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'AGX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AGYS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'AHCO', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AHR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'AIN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AIR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AIT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AKR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'ALG', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ALGM', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ALGT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ALHC', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ALK', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ALKS', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ALLY', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ALRM', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ALV', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'AM', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'AMG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'AMH', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'AMKR', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'AMN', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AMPH', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AMR', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'AMRX', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AMSF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'AMTM', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AMWD', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'ANDE', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'ANF', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'ANIP', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AORT', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AOSL', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'APAM', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'APG', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'APLE', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'APOG', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'APPF', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'AR', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'ARCB', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ARI', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'ARLO', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ARMK', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'AROC', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'ARR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'ARW', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ARWR', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ASB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ASGN', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ASH', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'ASO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'ASTE', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ASTH', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ATEN', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ATI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ATMU', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ATR', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'AUB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'AVA', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'AVAV', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AVNS', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AVNT', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'AVT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'AVTR', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AWI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AWR', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'AX', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'AXTA', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'AYI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'AZTA', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'AZZ', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'BAH', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'BANC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BANF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BANR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BBT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BBWI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BC', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BCC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'BCO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'BCPC', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'BDC', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'BFAM', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BFH', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BFS', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'BGC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BHE', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'BHF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BILL', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'BIO', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'BJ', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'BJRI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BKE', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BKH', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'BKU', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BL', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'BLD', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BLFS', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'BLKB', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'BMI', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'BMRN', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'BNL', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'BOH', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BOOT', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BOX', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'BRBR', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'BRC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'BRKR', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'BROS', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BRX', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'BSY', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'BTSG', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'BTU', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'BURL', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BWA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'BWXT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'BXMT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'BYD', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CABO', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'CACI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CAKE', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CALM', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'CALX', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'CALY', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CAR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CARG', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'CART', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'CASH', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CATY', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CAVA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CBRL', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CBSH', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CBT', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'CBU', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CC', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'CCK', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'CCOI', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'CCS', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CDP', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'CE', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'CELH', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'CENT', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'CENTA', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'CENX', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'CERT', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'CFFN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CFR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CGNX', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'CHCO', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CHDN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CHE', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'CHEF', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'CHH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CHRD', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'CHWY', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CLB', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'CLF', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'CLH', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CLSK', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'CMC', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'CNH', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CNK', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'CNM', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CNMD', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'CNO', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CNR', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'CNS', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CNX', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'CNXC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CNXN', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'COCO', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'COHU', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'COKE', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'COLB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'COLL', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'COLM', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CON', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'CORT', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'COTY', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'CPF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CPK', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'CPRI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CPRX', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'CR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CRBG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CRC', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'CRGY', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'CRI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CRK', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'CROX', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CRS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CRSR', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'CRUS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'CRVL', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'CSL', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CSR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'CSW', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CTKB', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'CTRE', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'CTS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'CUBE', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'CUBI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CURB', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'CUZ', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'CVBF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'CVCO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CVI', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'CVLT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'CVSA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'CW', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CWEN', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'CWEN.A', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'CWK', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'CWST', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CWT', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'CXM', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'CXT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'CXW', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'CYTK', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'CZR', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'DAN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'DAR', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'DBD', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'DBX', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'DCH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'DCI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'DCOM', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'DEA', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'DEI', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'DFH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'DFIN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'DGII', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'DINO', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'DIOD', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'DKS', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'DLB', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'DLX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'DNOW', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'DOCN', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'DOCS', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'DOCU', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'DORM', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'DRH', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'DT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'DTM', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'DUOL', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'DV', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'DXC', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'DXPE', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'DY', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'EAT', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'ECG', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ECPG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'EEFT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'EFC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'EGBN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'EGP', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'EHC', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'EIG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ELAN', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ELF', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'ELS', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'EMBC', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'EMN', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'ENOV', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ENPH', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ENR', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'ENS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ENSG', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ENTG', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ENVA', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'EPAC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'EPC', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'EPR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'EPRT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'EQH', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ESAB', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ESE', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ESI', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'ESNT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ETD', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'ETSY', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'EVR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'EVTC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'EWBC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'EXEL', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'EXLS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'EXP', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'EXPI', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'EXPO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'EXTR', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'EYE', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'EZPW', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FAF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FBIN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'FBK', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FBNC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FBP', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FBRT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'FCF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FCFS', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FCN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'FCPT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'FDP', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'FELE', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'FFBC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FFIN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FHB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FHI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FHN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FIBK', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FIVE', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'FIZZ', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'FLEX', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'FLG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FLO', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'FLR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'FLS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'FMC', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'FN', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'FNB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FND', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'FNF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FORM', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'FOUR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FOXF', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'FR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'FRPT', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'FSS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'FTDR', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'FTI', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'FTRE', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'FUL', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'FULT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'FUN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'FWRD', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'G', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'GAP', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'GATX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'GBCI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'GBX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'GDYN', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'GEF', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'GFF', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'GGG', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'GHC', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'GIII', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'GKOS', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'GLPI', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'GME', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'GMED', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'GNL', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'GNTX', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'GNW', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'GO', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'GOGO', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'GOLF', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'GPI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'GPK', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'GRBK', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'GSHD', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'GT', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'GTES', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'GTLS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'GTM', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'GTY', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'GVA', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'GWRE', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'GXO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'H', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'HAE', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'HAFC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HALO', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'HASI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HAYW', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'HCC', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'HCI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HCSG', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'HE', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'HFWA', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'HGV', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'HIMS', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'HIW', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'HL', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'HLI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HLIT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'HLNE', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HLX', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'HMN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HNI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'HOG', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'HOMB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HOPE', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HP', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'HQY', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'HR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'HRB', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'HRMY', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'HSTM', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'HTH', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HTLD', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'HTO', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'HTZ', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'HUBG', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'HWC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'HWKN', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'HXL', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'HZO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'IAC', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'IART', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'IBOC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'IBP', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'ICHR', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ICUI', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'IDA', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'IDCC', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'IIIN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'IIPR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'ILMN', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'INDB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'INDV', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'INGR', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'INSP', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'INSW', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'INVA', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'INVX', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'IOSP', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'IPAR', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'IPGP', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'IRDM', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'IRT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'ITGR', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ITRI', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ITT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'JAZZ', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'JBGS', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'JBLU', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'JBSS', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'JBTM', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'JEF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'JHG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'JJSF', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'JLL', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'JOE', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'JXN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'KAI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'KALU', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'KBH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'KBR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'KD', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'KEX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'KFY', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'KGS', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'KLIC', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'KMPR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'KMT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'KMX', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'KN', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'KNF', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'KNSL', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'KNTK', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'KNX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'KOP', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'KRC', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'KRG', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'KRYS', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'KSS', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'KTB', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'KTOS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'KW', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'KWR', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'LAD', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LAMR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'LAUR', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LBRT', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'LCII', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LEA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LECO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'LEG', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LFST', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'LFUS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'LGIH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LGND', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'LIF', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'LIVN', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'LKFN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'LKQ', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LMAT', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'LNC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'LNN', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'LNTH', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'LOPE', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LPG', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'LPX', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'LQDT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'LRN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LSTR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'LTC', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'LTH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'LUMN', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'LW', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'LXP', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'LYFT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'LZ', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'LZB', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'M', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MAC', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'MAN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MANH', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'MARA', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'MASI', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'MAT', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MATW', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MATX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MBC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MBIN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'MC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'MCRI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MCY', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'MD', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'MDU', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'MEDP', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'MGEE', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'MGY', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'MHK', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MHO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MIDD', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MIR', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'MKSI', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'MKTX', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'MLI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MLKN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MMI', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'MMS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MMSI', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'MNRO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MOG.A', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MOH', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'MORN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'MP', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'MPT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'MRCY', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MRP', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'MRTN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MSA', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MSEX', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'MSGS', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'MSM', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MTCH', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'MTDR', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'MTG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'MTH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MTN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MTRN', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'MTSI', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'MTUS', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'MTX', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'MTZ', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MUR', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'MUSA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'MWA', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MXL', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'MYRG', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'MZTI', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'NABL', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'NATL', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'NAVI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'NBHC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'NBIX', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'NBTB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'NE', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'NEO', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'NEOG', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'NEU', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'NFG', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'NGVT', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'NHC', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'NJR', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'NLY', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'NMIH', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'NNN', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'NOG', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'NOV', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'NOVT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'NPK', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'NPO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'NSA', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'NSIT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'NSP', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'NSSC', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'NTCT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'NTNX', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'NVRI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'NVST', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'NVT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'NWBI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'NWE', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'NWL', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'NWN', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'NX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'NXRT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'NXST', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'NXT', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'NYT', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'OC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'OFG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'OGE', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'OGN', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'OGS', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'OHI', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'OI', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'OII', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'OKTA', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'OLED', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'OLLI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'OLN', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'OMCL', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'ONB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ONTO', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'OPCH', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'OPLN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ORA', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'ORI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'OSIS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'OSK', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'OSW', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'OTTR', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'OUT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'OVV', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'OXM', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'OZK', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'P', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PAG', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PAHC', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'PARR', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'PATH', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PATK', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PAYC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'PAYO', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PBF', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'PBH', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'PBI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'PCRX', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'PCTY', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'PDFS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PEB', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'PECO', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'PEGA', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PEN', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'PENG', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PENN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PFBC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PFGC', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'PFS', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PGNY', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'PHIN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PI', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PII', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PINS', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'PIPR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PJT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PK', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'PLAB', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PLMR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PLNT', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PLUS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PLXS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PMT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'PNFP', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'POR', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'POST', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'POWI', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'POWL', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'PPC', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'PR', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'PRA', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PRAA', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PRDO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PRG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PRGO', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'PRGS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'PRI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'PRIM', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'PRKS', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PRLB', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'PRSU', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PRVA', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'PSMT', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'PSN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'PTCT', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'PTEN', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'PTGX', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'PVH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'PZZA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'QDEL', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'QLYS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'QNST', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'QRVO', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'QTWO', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'R', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'RAL', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'RAMP', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'RBA', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'RBC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'RCUS', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'RDN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'RDNT', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'RELY', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'RES', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'REX', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'REXR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'REYN', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'REZI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'RGA', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'RGEN', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'RGLD', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'RH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'RHI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'RHP', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'RITM', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'RLI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'RMBS', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'RNG', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'RNR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'RNST', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ROCK', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'ROG', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ROIV', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'RPM', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'RRC', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'RRR', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'RRX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'RS', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'RUN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'RUSHA', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'RWT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'RXO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'RYAN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'RYN', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'SABR', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SAFE', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'SAFT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SAH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SAIA', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'SAIC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'SAM', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'SANM', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'SARO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'SBCF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SBH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SBRA', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'SBSI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SCHL', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SCI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SCL', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'SCSC', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'SDGR', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'SEDG', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'SEIC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SEM', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'SEZL', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SFBS', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SFM', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'SFNC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SGI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SHAK', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SHC', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'SHEN', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'SHO', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'SHOO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SIG', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SIGI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SITM', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'SKT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'SKY', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SKYW', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'SLAB', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'SLG', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'SLGN', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'SLM', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SLVM', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'SM', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'SMG', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'SMP', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SMPL', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'SMTC', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'SN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SNDR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'SNEX', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SNX', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'SOLS', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'SON', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'SONO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'SPHR', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'SPNT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SPSC', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'SPXC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'SR', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'SRPT', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'SSB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SSD', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'SSTK', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'ST', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'STAA', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'STAG', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'STBA', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'STC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'STEL', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'STEP', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'STRA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'STRL', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'STWD', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'SUPN', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'SWX', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'SXI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'SXT', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'SYNA', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'TALO', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'TBBK', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'TCBI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'TDC', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'TDS', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'TDW', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'TEX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'TFIN', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'TFX', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'TGTX', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'THC', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'THG', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'THO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'THRM', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'TILE', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'TKR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'TLN', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'TMDX', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'TMHC', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'TNC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'TNDM', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'TNL', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'TOL', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'TR', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'TREX', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'TRIP', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'TRMK', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'TRN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'TRNO', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'TRST', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'TRU', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'TRUP', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'TTC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'TTEK', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'TTMI', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'TWLO', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'TWO', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'TXNM', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'TXRH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'UA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'UAA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'UBSI', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'UCB', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'UCTT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'UE', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'UFCS', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'UFPI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'UFPT', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'UGI', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'UHT', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'ULS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'UMBF', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'UNF', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'UNFI', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'UNIT', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'UNM', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'UPBD', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'UPWK', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'URBN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'USFD', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'USPH', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'UTHR', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'UTL', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'UVV', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'VAC', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'VAL', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'VC', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'VCEL', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'VCTR', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'VCYT', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'VECO', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'VFC', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'VGNT', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'VIAV', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'VICR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'VIR', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'VIRT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'VITL', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'VLY', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'VMI', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'VNO', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'VNOM', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'VNT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'VOYA', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'VRE', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'VRRM', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'VRTS', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'VSAT', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'VSCO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'VSEC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'VSH', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'VSNT', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'VSTS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'VTOL', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'VVV', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'VYX', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'WABC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WAFD', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WAL', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WAY', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'WBS', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WCC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'WD', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WDFC', sector: 'Consumer Staples', sectorEtf: 'XLP' },
  { ticker: 'WEN', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'WERN', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'WEX', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WFRD', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'WGO', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'WH', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'WHD', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'WHR', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'WINA', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'WING', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'WKC', sector: 'Energy', sectorEtf: 'XLE' },
  { ticker: 'WLK', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'WLY', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'WMG', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'WMS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'WOR', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'WPC', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'WRLD', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WS', sector: 'Materials', sectorEtf: 'XLB' },
  { ticker: 'WSC', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'WSFS', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WSO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'WSR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'WT', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WTFC', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WTRG', sector: 'Utilities', sectorEtf: 'XLU' },
  { ticker: 'WTS', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'WU', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'WWD', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'WWW', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'XHR', sector: 'Real Estate', sectorEtf: 'XLRE' },
  { ticker: 'XNCR', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'XPEL', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'XPO', sector: 'Industrials', sectorEtf: 'XLI' },
  { ticker: 'XRAY', sector: 'Healthcare', sectorEtf: 'XLV' },
  { ticker: 'YELP', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'YETI', sector: 'Consumer Discretionary', sectorEtf: 'XLY' },
  { ticker: 'YOU', sector: 'Technology', sectorEtf: 'XLK' },
  { ticker: 'ZD', sector: 'Communication Services', sectorEtf: 'XLC' },
  { ticker: 'ZION', sector: 'Financials', sectorEtf: 'XLF' },
  { ticker: 'ZWS', sector: 'Industrials', sectorEtf: 'XLI' },
];
